---
title: "Portfolio: Work in Progress!"
author: "Jack Krebsbach"
format:
  pdf:
    documentclass: article 
    toc-depth: 2
    toc: true
    number-sections: true
    colorlinks: true
    geometry:
        - top=30mm
        - left=30mm
        - right=30mm
        - heightrounded
---

\pagebreak

# About

I'm Jack Krebsbach, and I am currently pursuing a degree in Mathematics with a concentration in Statistics at Hope College in Holland, MI. I use data analysis and statistical learning methods to solve problems. I also enjoy learning about software development.


**Work in Progress**

\pagebreak
# Projects


**Work in Progress**
This is my portfolio showcasing various machine learning, data science, and data analysis problems I have worked on over the years.

## Sand dune modeling

**Work in Progress**
Modeling surface composition of Lake Michigan sand dunes


```{r}
#| echo: false
#| include: false

library(tidymodels)
tidymodels_prefer()
library(tidyverse)
```

## Spotify songs

Spotify song data analysis: Classifying song genre and predicting song popularity

## Sales conversion

**Work in Progress**
Predicting sales conversion from user data

## PCA Analysis

**Work in Progress**
PCA Analysis of Lake Michigan Sand Dunes
